#!/usr/bin/env node
//
// Generate packages/abis from Foundry build output + deployment records.
// Source of truth: contracts/execution/{out,deployments}. Output is COMMITTED
// so services build without forge and every ABI change shows up in the PR diff.
// Re-run after any contracts change:  pnpm --filter @numo/abis generate
//
import { readFileSync, writeFileSync, readdirSync, existsSync, mkdirSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const PKG = path.resolve(HERE, '..');                 // packages/abis
const ROOT = path.resolve(PKG, '..', '..');           // repo root
const EXEC = path.join(ROOT, 'contracts', 'execution');
const OUT_DIR = path.join(PKG, 'src', 'generated');

// Which compiled artifacts to surface, and under what export name.
const ARTIFACTS = [
  { export: 'matchingAbi', artifact: 'out/Matching.sol/Matching.json' },
  { export: 'tradeModuleAbi', artifact: 'out/ITradeModule.sol/ITradeModule.json' },
];

function readAbi(rel) {
  const p = path.join(EXEC, rel);
  if (!existsSync(p)) throw new Error(`missing artifact: ${p} (run \`forge build\` in contracts/execution first)`);
  const json = JSON.parse(readFileSync(p, 'utf8'));
  if (!json.abi) throw new Error(`artifact has no abi: ${p}`);
  return json.abi;
}

function readDeployments() {
  const dir = path.join(EXEC, 'deployments');
  const out = {};
  if (!existsSync(dir)) return out;
  for (const chainId of readdirSync(dir)) {
    const f = path.join(dir, chainId, 'matching.json');
    if (!existsSync(f)) continue;
    const raw = JSON.parse(readFileSync(f, 'utf8'));
    if (!raw.matching || !raw.trade) continue;          // skip incomplete records
    out[chainId] = { matching: raw.matching, trade: raw.trade };
  }
  return out;
}

const BANNER = '// AUTO-GENERATED by scripts/generate.mjs — do not edit by hand.\n\n';

mkdirSync(OUT_DIR, { recursive: true });

// abis.ts
let abisTs = BANNER;
for (const a of ARTIFACTS) {
  abisTs += `export const ${a.export} = ${JSON.stringify(readAbi(a.artifact), null, 2)} as const;\n\n`;
}
writeFileSync(path.join(OUT_DIR, 'abis.ts'), abisTs);

// deployments.ts
const deployments = readDeployments();
const depTs =
  BANNER +
  `export const deployments = ${JSON.stringify(deployments, null, 2)} as const;\n\n` +
  `export type ChainId = keyof typeof deployments;\n`;
writeFileSync(path.join(OUT_DIR, 'deployments.ts'), depTs);

console.log(
  `generated ${ARTIFACTS.length} ABIs and ${Object.keys(deployments).length} deployment(s): ` +
  Object.keys(deployments).join(', ')
);
