# State lives in S3, not on a laptop. This is not optional hygiene here: the RDS
# password is generated by random_password, so terraform.tfstate contains a live
# production credential whether or not the executor key stays out of it.
#
# The bucket is created out of band — it cannot be managed by the state it stores:
#
#   aws s3api create-bucket --bucket numo-terraform-state-957261948743 --region us-east-1
#   aws s3api put-bucket-versioning  --bucket ... --versioning-configuration Status=Enabled
#   aws s3api put-bucket-encryption  --bucket ... (aws:kms, bucket key enabled)
#   aws s3api put-public-access-block --bucket ... (all four blocks true)
#
# use_lockfile is S3-native locking (Terraform >= 1.10), so there is no DynamoDB
# table to own.
terraform {
  backend "s3" {
    bucket       = "numo-terraform-state-957261948743"
    key          = "exchange/terraform.tfstate"
    region       = "us-east-1"
    encrypt      = true
    use_lockfile = true
  }
}
